import mongoose from 'mongoose';

const SessionSchema = new mongoose.Schema({
  client: { type: mongoose.Schema.Types.ObjectId, ref: 'Client', required: true },
  technician: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  date: { type: Date, default: Date.now },
  durationMinutes: { type: Number, required: true },
  
  // The raw data collected during the shift
  behaviorData: [{
    behaviorName: String,
    frequency: Number
  }],
  
  // The note generated by the LLM API
  aiDraftedNote: { type: String },
  status: { type: String, enum: ['DRAFT', 'APPROVED'], default: 'DRAFT' }
}, { timestamps: true });

export default mongoose.models.Session || mongoose.model('Session', SessionSchema);